language: node_js
sudo: required
services:
  - docker

before_install:
  - docker build -t kd:react -f Dockerfile.dev . 

script:
  - docker run kd:react npm run test -- --coverage  

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-116290078868"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_acces_key:
    secure: "$AWS_SECRET_KEY"